const ORDER_MODULE = [
	{
		id: 'shopOrderBill',
		label: '门店订货单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-shopOrder.png'),
		waring: '0',
		showFlag: true,
		path: '/shopOrder',
		auth: 'shopOrderBill',
		defaultCreatePath: '/createShopOrder'
	}, {
		id: 'distributionInBill',
		label: '统配入库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-unifyOrder.png'),
		waring: '0',
		showFlag: true,
		path: '/unifyOrder',
		auth: 'distributionInBill'
	}, {
		id: 'shopDirectInBill',
		label: '直送入库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-sendOrder.png'),
		waring: '0',
		showFlag: true,
		path: '/sendOrder',
		auth: 'shopDirectInBill'
	}, {
		id: 'shopStraightInBill',
		label: '直通入库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-directOrder.png'),
		waring: '0',
		showFlag: true,
		path: '/directOrder',
		auth: 'shopStraightInBill'
	}, {
		id: 'shopMoveApplyBill',
		label: '调拨申请单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-moveOrder.png'),
		waring: '0',
		showFlag: true,
		path: '/moveOrder',
		auth: 'shopMoveApplyBill'
	}, {
		id: 'shopCheckBill',
		label: '盘点单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-checkBill.png'),
		waring: '0',
		showFlag: true,
		path: '/checkBill',
		auth: 'shopCheckBill'
	}, {
		id: 'shopDirectRtnBill',
		label: '直送退货单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-sendReturnOrder.png'),
		waring: '0',
		showFlag: true,
		path: '/sendReturnOrder',
		auth: 'shopDirectRtnBill'
	}, {
		id: 'shopStockInBill',
		label: '采购入库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-stockInBill.png'),
		waring: '0',
		showFlag: true,
		path: '/stockInBill',
		auth: 'shopStockInBill'
	}, {
		id: 'stockApplyBill',
		label: '采购申请单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-stockApply.png'),
		waring: '0',
		showFlag: true,
		path: '/stockApply',
		auth: 'stockApplyBill'
	}, {
		id: 'stockApplySend',
		label: '采购申请分派',
		iconSrc: require('@/assets/images/icon/order-logo/icon-stockApplySend.png'),
		waring: '0',
		showFlag: true,
		path: '/stockApplySend',
		auth: 'stockApplySend'
	}, {
		id: 'shopMoveOutBill',
		label: '调拨出库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-shopMoveOut.png'),
		waring: '0',
		showFlag: true,
		path: '/shopMoveOut',
		auth: 'shopMoveOutBill'
	}, {
		id: 'shopMoveInBill',
		label: '调拨入库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-shopMoveIn.png'),
		waring: '0',
		showFlag: true,
		path: '/shopMoveIn',
		auth: 'shopMoveInBill'
	}, {
		id: 'distributionOutBill',
		label: '统配出库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-uniformDistributionOut.png'),
		waring: '0',
		showFlag: true,
		path: '/uniformDistributionOut',
		auth: 'distributionOutBill'
	}, {
		id: 'otherOutBill',
		label: '其他出库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-otherOut.png'),
		waring: '0',
		showFlag: true,
		path: '/otherOut',
		auth: 'otherOutBill'
	}, {
		id: 'stockOrderBill',
		label: '采购订货单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-stockOrder.png'),
		waring: '0',
		showFlag: true,
		path: '/stockOrder',
		auth: 'stockOrderBill'
	}, {
		id: 'departmentReceiveBill',
		label: '部门领用单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-departmentReceive.png'),
		waring: '0',
		showFlag: true,
		path: '/departmentReceive',
		auth: 'departmentReceiveBill'
	}, {
		id: 'salesOutBill',
		label: '外销出库单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-salesOut.png'),
		waring: '0',
		showFlag: true,
		path: '/salesOut',
		auth: 'salesOutBill'
	}, {
		id: 'breakBill',
		label: '报损单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-breakBill.png'),
		waring: '0',
		showFlag: true,
		path: '/breakBill',
		auth: 'breakBill'
	}, {
		id: 'insideMoveBill',
		label: '内部调拨单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-insideMoveBill.png'),
		waring: '0',
		showFlag: true,
		path: '/insideMoveBill',
		auth: 'insideMoveBill'
	}, {
		id: 'uniformDistributionRtnBill',
		label: '统配退货单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-uniformDistributionRtnBill.png'),
		waring: '0',
		showFlag: true,
		path: '/uniformDistributionRtnBill',
		auth: 'uniformDistributionRtnBill'
	}, {
		id: 'foodSamplBill',
		label: '菜品留样',
		iconSrc: require('@/assets/images/icon/order-logo/icon-foodSamples.png'),
		waring: '0',
		showFlag: true,
		moduleType: 'foodSafe', // foodSafe代表食品安全模块
		path: '/foodSamples',
		auth: 'foodSamplBill'
	}, {
		id: 'carBill',
		label: '加工单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-uniformDistributionRtnBill.png'),
		waring: '0',
		showFlag: true,
		path: '/carBill',
		auth: 'carBill'
	}, {
		id: 'shopStraightRtnBill',
		label: '门店直通退货单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-shopStraightRtnBill.png'),
		waring: '0',
		showFlag: true,
		path: '/shopStraightRtnBill',
		auth: 'shopStraightRtnBill'
	}, {
		id: 'foodReckonBill',
		label: '菜品预估单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-foodReckonBill.png'),
		waring: '0',
		showFlag: true,
		path: '/foodReckonBill',
		auth: 'foodReckonBill'
	}, {
		id: 'shopReturnBill',
		label: '采购退货单',
		iconSrc: require('@/assets/images/icon/order-logo/icon-shopReturnBill.png'),
		waring: '0',
		showFlag: true,
		path: '/shopReturnBill',
		auth: 'shopReturnBill'
	}
]
export default ORDER_MODULE
